### ISSUE TITLE
Wildstacker make Mypet pets instant respawn

### ISSUE THREAD

**Issue by netherstar** [OmerBenGera/WildStacker#16] opened 2021-01-12 14:01 UTC
As you can see in this gif, pet respawn instant
https://imgur.com/a/Ce37eQi
When not install wildstacker, pet need to wait a time to respawn
Wildstacker build 21 (latest version)
Paperspigot 1.12.2
This is config file of wildstacker: https://paste.ubuntu.com/p/RqPs5DRF8f/

**Comment by OmerBenGera** [comment] 2021-01-12 14:16
Send me your config of MyPet please

**Comment by netherstar** [comment] 2021-01-12 14:18
> Send me your config of MyPet please

here are mypet config: https://paste.ubuntu.com/p/7zkGxZTG97/

**Comment by OmerBenGera** [comment] 2021-01-12 14:21
> 
> 
> > Send me your config of MyPet please
> 
> here are mypet config: https://paste.ubuntu.com/p/7zkGxZTG97/
> I'm using old Mypet version 2.3.9

I'll check that out, thanks

**Comment by netherstar** [comment] 2021-01-12 14:27
you can download Mypet from here: https://mypet-plugin.de/download
I'm just test latest version of Mypet, i confirm that latest version same issue

**Comment by OmerBenGera** [comment] 2021-01-12 15:10
Fixed in build #28

**Comment by netherstar** [comment] 2021-01-12 15:33
i'm just tested, i confirm it is fixed but every time pet be killed this show on console
```
[22:31:21 WARN]: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
[22:31:21 WARN]:        at com.google.common.base.Absent.get(Absent.java:45)
[22:31:21 WARN]:        at de.Keyle.MyPet.compat.v1_12_R1.entity.ai.movement.Control.shouldStart(Control.java:53)
[22:31:21 WARN]:        at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:104)
[22:31:21 WARN]:        at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1017)
[22:31:21 WARN]:        at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:933)
[22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:2024)
[22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:247)
[22:31:21 WARN]:        at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1206)
[22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797)
[22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.World.h(World.java:1767)
[22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1574)
[22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682)
[22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921)
[22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[22:31:21 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by OmerBenGera** [comment] 2021-01-12 16:01
> 
> 
> i'm just tested, i confirm it is fixed but every time pet be killed this show on console
> 
> ```
> [22:31:21 WARN]: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
> [22:31:21 WARN]:        at com.google.common.base.Absent.get(Absent.java:45)
> [22:31:21 WARN]:        at de.Keyle.MyPet.compat.v1_12_R1.entity.ai.movement.Control.shouldStart(Control.java:53)
> [22:31:21 WARN]:        at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:104)
> [22:31:21 WARN]:        at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1017)
> [22:31:21 WARN]:        at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:933)
> [22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:2024)
> [22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:247)
> [22:31:21 WARN]:        at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1206)
> [22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797)
> [22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.World.h(World.java:1767)
> [22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1574)
> [22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682)
> [22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921)
> [22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
> [22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
> [22:31:21 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
> [22:31:21 WARN]:        at java.lang.Thread.run(Thread.java:748)
> ```

Do you think it's related to WildStacker?
It looks like an issue that comes from de.Keyle.MyPet.compat.v1_12_R1.entity.ai.movement.Control.shouldStart

If you believe it was caused by WS, let me know and I'll check that out

**Comment by netherstar** [comment] 2021-01-12 16:02
i'm sure this only happen after i install Wildstacker build 28.

**Comment by OmerBenGera** [comment] 2021-01-12 18:46
@netherstar I looked into their code and I am not sure what causes it.
Try contacting their developer, maybe they can find the cause and let me know why it breaks
Send them a link to this github if possible

**Comment by OmerBenGera** [comment] 2021-01-16 16:11
Any news regarding this?

**Comment by netherstar** [comment] 2021-01-16 16:17
> Any news regarding this?

MyPet's  author seem to be inactive, i can't contact him.

**Comment by OmerBenGera** [comment] 2021-01-16 16:44
How can I replicate the error myself?

**Comment by netherstar** [comment] 2021-01-16 16:57
> How can I replicate the error myself?

just kill other player's pet, not always happen but at least  90% this error appear

**Comment by netherstar** [comment] 2021-01-16 17:00
using command to make other player pet: /petadmin create -f Player chicken
and than kill it

**Comment by OmerBenGera** [comment] 2021-01-16 17:15
I killed around 10 chickens and couldn't replicate the issue.
Are you able to replicate it with default WS config file? Maybe it's something related to that

**Comment by netherstar** [comment] 2021-01-16 17:31
> I killed around 10 chickens and couldn't replicate the issue.
> Are you able to replicate it with default WS config file? Maybe it's something related to that

on my server, mypet version is Mypet premium 2.39, with wildstacker build 28 it fix pet instant respawn issue but show error like i said.
i'm just test with Mypet 3.1 (latest version) and wildstacker b28, it is not fix pet instant respawn issue so error like i said not appear. May be you using Mypet 3.1?

**Comment by OmerBenGera** [comment] 2021-01-16 17:37
I am using MyPet v3.11, and it has no issues with instant spawn.

**Comment by netherstar** [comment] 2021-01-16 18:12
> I am using MyPet v3.11, and it has no issues with instant spawn.

i'm using clean install
Mypet 3.11
Wildstacker-b33

All default config, i'm sure pet instant respawn issue still not fixed.

**Comment by OmerBenGera** [comment] 2021-01-16 18:22
It works fine for me, I am not sure how it doesn't work for you

**Comment by OmerBenGera** [comment] 2021-01-16 18:22
Pets spawn after 5 seconds after being killed

**Comment by netherstar** [comment] 2021-01-16 18:29
> Pets spawn after 5 seconds after being killed

oh i see, default mypet respawn is 5 seconds.
So with Latest version of Mypet this issue is fixed.
This is issue with Mypet old version. Just update Mypet.

**Closed** 2021-01-16 18:31 UTC
