### ISSUE TITLE
Chunk Load Error (More than likely due to AdvancedSpawners)

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [OmerBenGera/WildStacker#76] opened 2021-03-12 23:01 UTC
https://pastebin.com/WABL850t

Was stood afk for an extended period of time next to a custom spawner from advancedspawners

**Comment by OmerBenGera** [comment] 2021-03-13 08:42
Duplicate of #74

**Closed by OmerBenGera** 2021-03-13 08:42 UTC
