### ISSUE TITLE
Dolphins Spawners don't spawn dolphins

### ISSUE THREAD

**Issue by Nekosity12** [OmerBenGera/WildStacker#10] opened 2021-01-07 15:57 UTC
https://youtu.be/z6FhAT0lWJM

Above is the video we recorded where dolphin spawners refused to spawn dolphins. Natural dolphins would spawn just fine and we were between y45 and y60 in an ocean biome with an open sky just incase there were any spawn conditions. We tried placing the spawner in many different ways to see if they would spawn to no avail.

This is sort of related to the issue, would there be a way to spawn with no restrictions as well, i.e. if we wanted to spawn slimes instead of putting the spawner in a slime chunk we could just put it down anywhere and they'll spawn? Would be a tremendous help especially since it is difficult to test if this is just a bug or if we're missing a spawn condition :/

**Comment by OmerBenGera** [comment] 2021-01-07 16:48
What minecraft version are you using? I'll try to replicate it on my server

**Comment by Soapiee** [comment] 2021-01-07 18:16
The Minecraft server is 1.16.4
Jar = Yatopia b34
Also tested on another server with the jar = Yatopia b11

**Comment by OmerBenGera** [comment] 2021-01-07 18:36
After another check, I saw that you try to spawn dolphins in an ocean biome.
However, dolphins can't spawn in oceans by default. You can remove their spawn conditions if your server runs on a Java version below 12

**Comment by Soapiee** [comment] 2021-01-07 19:01
On the Minecraft Wiki it says Dolphins spawn in all ocean biomes (https://gyazo.com/d4d2a5b3eb65ca56dbfa897b7b891598).

We are also on Java version 1.8 at the moment and are looking to update in the future once we have confirmed all plugin compatibility.

**Comment by OmerBenGera** [comment] 2021-01-07 19:07
> 
> 
> On the Minecraft Wiki it says Dolphins spawn in all ocean biomes (https://gyazo.com/d4d2a5b3eb65ca56dbfa897b7b891598).
> 
> We are also on Java version 1.8 at the moment and are looking to update in the future once we have confirmed all plugin compatibility.

I also saw that in the wiki, not sure why that's written there. Dolphins spawn in water that above level 45 and below sea level, but not in oceans or deep oceans.

**Comment by Soapiee** [comment] 2021-01-07 19:15
Oh wow, that is very irritating...thank you for the information.

Even though we are less than Java 12 the spawn conditions still need to be met. Is Java 1.8 too low?

**Comment by OmerBenGera** [comment] 2021-01-07 19:33
> 
> 
> Oh wow, that is very irritating...thank you for the information.
> 
> Even though we are less than Java 12 the spawn conditions still need to be met. Is Java 1.8 too low?

You can edit the spawn conditions of them if you use Java 1.8

**Comment by Skizzles** [comment] 2021-01-07 20:11
@OmerBenGera 

Do the spawn conditions work on Java 14? Or would this need to be tested?

As we are looking to move to Java 14 as Yatopia uses things from it.

**Comment by OmerBenGera** [comment] 2021-01-07 20:31
> 
> 
> @OmerBenGera
> 
> Do the spawn conditions work on Java 14? Or would this need to be tested?
> 
> As we are looking to move to Java 14 as Yatopia uses things from it.

Spawn conditions cannot work in Java 14 due to changes in Java 12 that prevent the system from working

**Comment by Skizzles** [comment] 2021-01-07 22:53
After looking into this more... I believe dolphins are supposed to spawn in the ocean based off vanilla mc behavior. Currently they spawn in everywhere in those y levels EXCEPT oceans which is odd.

**Comment by OmerBenGera** [comment] 2021-01-07 23:04
> After looking into this more... I believe dolphins are supposed to spawn in the ocean based off vanilla mc behavior. Currently they spawn in everywhere in those y levels EXCEPT oceans which is odd.

Dolphins dont spawn in oceans based on the code of 1.16.4 paper.
I am closing this issue for now

**Closed by OmerBenGera** 2021-01-07 23:04 UTC
