### ISSUE TITLE
Breaking or trying to give 128 spawners throws errors.

### ISSUE THREAD

**Issue by MythricHD** [OmerBenGera/WildStacker#25] opened 2021-01-26 06:38 UTC
Currently on Build 36 but also tested on build 42. Here is the console error: https://paste.helpch.at/ivipaworas.md

Happens whenever I try to use the stacker command to give 128 spawners or break any spawner stack 128 or above. 
Seems like a weird one. Also here is a video of it happening: https://www.youtube.com/watch?v=Mdx1zusEpGA&feature=youtu.be

**Comment by OmerBenGera** [comment] 2021-01-26 09:12
Show me your config please - upload it to pastebin

**Comment by MythricHD** [comment] 2021-01-26 16:35
Here is my config: https://paste.helpch.at/jovaceziyu.bash

**Comment by OmerBenGera** [comment] 2021-01-26 19:04
> 
> 
> Here is my config: https://paste.helpch.at/jovaceziyu.bash
> 
> Also unrelated question but is there a way to stop mobs spawning with armor? (zombies, skeletons)

You can only disable it using other plugins

**Comment by OmerBenGera** [comment] 2021-01-26 19:15
I can't seem to replicate the issue. Are you able to replicate it with the default config file?

**Comment by MythricHD** [comment] 2021-01-27 04:39
Sorry I forgot to mention that the spawner needs to be upgraded

**Comment by OmerBenGera** [comment] 2021-01-29 16:29
Build 48 will fix the issue :)

**Comment by MythricHD** [comment] 2021-01-29 21:16
Tested with b51, no longer getting error in console but if the upgraded stack is above 128 I still do not get the spawners put in my inventory

**Comment by OmerBenGera** [comment] 2021-01-30 10:37
It works fine for me

**Comment by TouchBrown** [comment] 2021-01-30 22:48
I'm with Myth and here is a video of it happening with no other plugins https://youtu.be/SfFxpQfDaz8

**Comment by TouchBrown** [comment] 2021-01-31 20:03
Another relevant note we use this config option which you may not have been using drop-stacked-item: false

**Comment by OmerBenGera** [comment] 2021-01-31 21:23
> 
> 
> Another relevant note we use this config option which you may not have been using drop-stacked-item: false

Of course I had it disabled :P
I will try replicating it again with your config tomorrow hopefully

**Comment by OmerBenGera** [comment] 2021-02-01 18:22
I just tried to replicate the issue and can't seem to get it working.
What mc version are you using?

**Comment by TouchBrown** [comment] 2021-02-01 20:26
1.12.2

**Comment by OmerBenGera** [comment] 2021-02-03 10:35
I tried it with 1.12.2 and it worked for me...
Are you able to replicate the issue with only WildStacker installed?

**Comment by TouchBrown** [comment] 2021-02-03 17:12
yeah only wildstacker with default config set drop-stacked-item: false for spawners and i tested with ig spawners, but all I did for that was put the upgrade spawner type to IRON_GOLEM.  I did again test it with vault and essentials and had the same issue.  Not sure why its working for you

**Comment by OmerBenGera** [comment] 2021-02-05 17:03
What gamemode are you in when breaking the spawners?

**Comment by TouchBrown** [comment] 2021-02-05 22:37
Survival

**Comment by OmerBenGera** [comment] 2021-02-06 09:37
I really don't know what the issue is, it works fine for me - I can break spawners with more than 128 and still receive them, even if they are upgraded.

**Comment by OmerBenGera** [comment] 2021-02-06 09:44
Take a clip of the issue please - make sure you show the pickaxe that you use for breaking the spawners in the video

**Comment by TouchBrown** [comment] 2021-02-07 01:42
https://youtu.be/2RTaX1OBlCY note default config but i set drop-stacked-item: false in config under spawners and i made the upgrades for mob iron_golem.  Version is 1.12.2 paper with no plugins other than essentials vault and wildstacker.  Pickaxe is only silktouch

**Comment by OmerBenGera** [comment] 2021-02-07 10:58
Probably an issue with your paper version.
Which version exactly of Paper are you using?

**Comment by TouchBrown** [comment] 2021-02-07 19:49
version 1618 here is the download if you want to try directly https://papermc.io/api/v2/projects/paper/versions/1.12.2/builds/1618/downloads/paper-1.12.2-1618.jar

**Comment by TouchBrown** [comment] 2021-02-09 01:18
Do you mind sending a video of what you're doing and a quick description of changes to the config you made if it's working for you?

**Comment by OmerBenGera** [comment] 2021-02-09 08:55
The changes I made are to set drop-stacked-item to false and make the default upgrade to support an entity. Then, I gave myself a silktouch pickaxe and broke an upgraded spawner with like 300 spawners.

**Comment by TouchBrown** [comment] 2021-02-09 19:07
Hmm so i've done a little more testing, but even when its below 128 you get the spawners with the name as the upgrade, but when you place them down it no longer is an upgraded spawner and you have to buy the upgrades again.

**Comment by TouchBrown** [comment] 2021-02-11 19:05
looks like issue #45 is having the same issue

**Comment by OmerBenGera** [comment] 2021-02-12 23:37
> 
> 
> looks like issue #45 is having the same issue

The issues are not even the same, how did you come to that conclusion?

**Comment by TouchBrown** [comment] 2021-02-13 01:05
When I said even if you do get the stack back from mining because you mine less than 128 the spawners are not upgraded

**Comment by TouchBrown** [comment] 2021-02-14 18:28
ok so I did a bunch of testing and I think I know the issue.  This is a problem in give command and breaking upgraded spawners, but the way you are adding the nbt data to the itemstack is returning no itemstack because for whatever reason when you use CraftItemStack.asNMSCopy if the itemstack is over 127 it returns nothing.  One way around this is setting the nbt first then setting the amount by moving this https://github.com/OmerBenGera/WildStacker/blob/cdfd7c4dbfddbc75b2997e0bba0efc688e13bdd9/src/main/java/com/bgsoftware/wildstacker/command/commands/CommandGive.java#L164-L165 up to line 155.  Then do the same in the spawner providers for example in default move https://github.com/OmerBenGera/WildStacker/blob/346ab78bc21b33d5aaf10765d4f83839b8cf7e03/src/main/java/com/bgsoftware/wildstacker/hooks/SpawnersProvider_Default.java#L48-L49 to line 39.
Of course there are probably better ways, but i'm just showing examples to help explain.
Now this will solve the 128 issue, but the spawners when broken still dont give the nbt for the spawner upgrade.  My only guess as of now is that maybe this line https://github.com/OmerBenGera/WildStacker/blob/346ab78bc21b33d5aaf10765d4f83839b8cf7e03/src/main/java/com/bgsoftware/wildstacker/hooks/SpawnersProvider_Default.java#L79 since it comes after setting the nbt I wonder if it removes it.  Quick note I just tested this and since you set item meta after setting the nbt it removes the nbt.

**Comment by TouchBrown** [comment] 2021-02-14 18:29
^ that last thing I mentioned will fix issue #45 too

**Comment by TouchBrown** [comment] 2021-02-14 21:54
ok I figured out what the issue is I think.  When you moved this https://github.com/OmerBenGera/WildStacker/blob/cdfd7c4dbfddbc75b2997e0bba0efc688e13bdd9/src/main/java/com/bgsoftware/wildstacker/hooks/SpawnersProvider_Default.java#L59 below the try catch it stopped giving the nbt.  I just tested the function before and after the commit where you moved it and that's when it stopped working.

**Comment by OmerBenGera** [comment] 2021-02-16 13:08
I fixed the spwaner upgrades thingy, let me know if it fixed the amounts as well or not

**Comment by TouchBrown** [comment] 2021-02-16 13:14
`org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:322) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:221) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:948) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
        at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.getSpawnerItem(SpawnersProvider_Default.java:66) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.getSpawnerItem(ProvidersHandler.java:224) ~[?:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.getDropItem(WStackedSpawner.java:397) ~[?:?]
        at com.bgsoftware.wildstacker.utils.events.EventsCaller.callSpawnerDropEvent(EventsCaller.java:91) ~[?:?]
        at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.dropSpawner(SpawnersProvider_Default.java:146) ~[?:?]
        at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.handleSpawnerBreak(SpawnersProvider_Default.java:133) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.handleSpawnerBreak(ProvidersHandler.java:236) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.SpawnersListener.handleSpawnerBreak(SpawnersListener.java:312) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockBreak(SpawnersListener.java:293) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor110.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]`

**Comment by TouchBrown** [comment] 2021-02-16 13:18
`org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:322) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:221) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:948) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
	at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.getSpawnerItem(SpawnersProvider_Default.java:66) ~[?:?]
	at com.bgsoftware.wildstacker.handlers.ProvidersHandler.getSpawnerItem(ProvidersHandler.java:224) ~[?:?]
	at com.bgsoftware.wildstacker.objects.WStackedSpawner.getDropItem(WStackedSpawner.java:397) ~[?:?]
	at com.bgsoftware.wildstacker.utils.events.EventsCaller.callSpawnerDropEvent(EventsCaller.java:91) ~[?:?]
	at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.dropSpawner(SpawnersProvider_Default.java:146) ~[?:?]
	at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.handleSpawnerBreak(SpawnersProvider_Default.java:133) ~[?:?]
	at com.bgsoftware.wildstacker.handlers.ProvidersHandler.handleSpawnerBreak(ProvidersHandler.java:236) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.SpawnersListener.handleSpawnerBreak(SpawnersListener.java:312) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockBreak(SpawnersListener.java:293) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor110.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
	... 17 more`

**Comment by TouchBrown** [comment] 2021-02-16 13:18
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:322) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:221) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:948) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
	at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.getSpawnerItem(SpawnersProvider_Default.java:66) ~[?:?]
	at com.bgsoftware.wildstacker.handlers.ProvidersHandler.getSpawnerItem(ProvidersHandler.java:224) ~[?:?]
	at com.bgsoftware.wildstacker.objects.WStackedSpawner.getDropItem(WStackedSpawner.java:397) ~[?:?]
	at com.bgsoftware.wildstacker.utils.events.EventsCaller.callSpawnerDropEvent(EventsCaller.java:91) ~[?:?]
	at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.dropSpawner(SpawnersProvider_Default.java:146) ~[?:?]
	at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.handleSpawnerBreak(SpawnersProvider_Default.java:133) ~[?:?]
	at com.bgsoftware.wildstacker.handlers.ProvidersHandler.handleSpawnerBreak(ProvidersHandler.java:236) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.SpawnersListener.handleSpawnerBreak(SpawnersListener.java:312) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockBreak(SpawnersListener.java:293) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor110.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
	... 17 more

**Comment by OmerBenGera** [comment] 2021-02-16 13:23
Try latest dev build, pushed another update that should fix it

**Comment by TouchBrown** [comment] 2021-02-16 13:32
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:322) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:221) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:948) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
        at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.getSpawnerItem(SpawnersProvider_Default.java:67) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.getSpawnerItem(ProvidersHandler.java:224) ~[?:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.getDropItem(WStackedSpawner.java:397) ~[?:?]
        at com.bgsoftware.wildstacker.utils.events.EventsCaller.callSpawnerDropEvent(EventsCaller.java:91) ~[?:?]
        at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.dropSpawner(SpawnersProvider_Default.java:147) ~[?:?]
        at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.handleSpawnerBreak(SpawnersProvider_Default.java:134) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.handleSpawnerBreak(ProvidersHandler.java:236) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.SpawnersListener.handleSpawnerBreak(SpawnersListener.java:312) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockBreak(SpawnersListener.java:293) ~[?:?]

**Comment by OmerBenGera** [comment] 2021-02-16 13:35
Jesus my bad, check out latest dev build.
Sorry about all of that mess, I can't replicate the issue so I just upload the jars so you can test them

**Comment by TouchBrown** [comment] 2021-02-16 13:36
would it be impractical to set pass in the itemstack and set a variable with the amount of the item stack and set the itemstack to 1 then give the nbt and before returning setting it back to the itemstack size here https://github.com/OmerBenGera/WildStacker/blob/fd4d89fbead8cbdae6fffecbb5ef94496561c5f5/v1_12_R1/src/main/java/com/bgsoftware/wildstacker/nms/NMSAdapter_v1_12_R1.java#L621 because the item is returning null as that is what happens when you try to go over 128

**Comment by TouchBrown** [comment] 2021-02-16 13:37
well the problem is the itemstack is null because when you pass it through the setSpawnerUpgrade it takes the itemstack and tries to nmsCopy it but it can't since the item stack is over 128

**Comment by OmerBenGera** [comment] 2021-02-16 13:39
I changed it in latest dev build...

**Comment by TouchBrown** [comment] 2021-02-16 13:42
looks like that worked!  Only issue now is that its still an issue on the give command.  No error it just doesnt give you anything if it is above 127

**Comment by TouchBrown** [comment] 2021-02-16 13:42
when giving an upgraded spawner

**Comment by OmerBenGera** [comment] 2021-02-16 13:43
Perfect :)
gonna check the give command now

**Comment by TouchBrown** [comment] 2021-02-16 13:45
looks like this is why https://github.com/OmerBenGera/WildStacker/blob/f8a1f9bf62557d4e7121239bc3d169d372aec3fa/src/main/java/com/bgsoftware/wildstacker/command/commands/CommandGive.java#L164 you upgrade again even though you do it in getSpawnerItem

**Comment by OmerBenGera** [comment] 2021-02-16 13:45
Check out latest dev build, I removed this part as it's not needed :)

**Comment by TouchBrown** [comment] 2021-02-16 13:46
perfect :) everything works from what I can tell right now

**Comment by OmerBenGera** [comment] 2021-02-16 13:56
Great - if the issue continues, let me know :)

**Closed by OmerBenGera** 2021-02-16 13:56 UTC
Labels: Bug Report, Needs investigation
