### ISSUE TITLE
The spawners stop working after a while.

### ISSUE THREAD

**Issue by Requlogia** [OmerBenGera/WildStacker#88] opened 2021-03-19 22:31 UTC
The spawners stop working after a while.
This problem only occurs with zombie, skeleton and zombie pigman spawners.
When I break the spawner and put it in another area, it continues to work, but it doesn't work when I put it back in the old area.
When I put another spawner in the old area where the spawner was, the other spawner I put in continues to work. (For example: The zombie spawner does not work in the field, it only works when I break it and place a skeleton spawner instead.
When I restart my server, spawners in the non-working area start working again.

**Server version:** 1.12.2
**Fork:** PaperSpigot
**Plugin version:** 3.4.3

**Comment by OmerBenGera** [comment] 2021-03-20 13:26
Sounds like you just don't meet the requirements to spawn the mobs.
There's no reason for spawners to stop working out of nowhere.
Try overriding the spawn conditions and make them empty, so there will be no restrictions.

**Comment by Requlogia** [comment] 2021-03-20 14:37
When I restart the server they are already working as before. After a while, they stop working. I don't think it will have anything to do with the circumstances. This problem only occurs in zombie, skeleton and zombie pigman spawner. I have already explained this problem above. The conditions are already met.

**Comment by OmerBenGera** [comment] 2021-03-20 16:32
> When I restart the server they are already working as before. After a while, they stop working. I don't think it will have anything to do with the circumstances. This problem only occurs in zombie, skeleton and zombie pigman spawner. I have already explained this problem above. The conditions are already met.

There's no difference between skeletons, zombies and zombie pigmans or any other mob, therefore if it was an issue with the plugin, it would occur with all the spawners.
Try opening the spawners menu, let me know if it fixes the issue

**Comment by Requlogia** [comment] 2021-03-20 16:34
I don't think the problem can be solved this way. Thanks anyway.

**Comment by OmerBenGera** [comment] 2021-03-20 17:02
When opening the spawners menu, WildStacker makes sure the spawner ia still overridden by the plugin.
Instead of arguing, maybe do what I say so we can find the problem?

**Comment by Requlogia** [comment] 2021-03-20 17:42
I don't have the problem right now, because I restarted my server, the spawners started working, but I'm sure it will stop again after a while. (Not everyone's spawners stop, it stop in a certain area.) I'll try if the problem happens again.

**Comment by OmerBenGera** [comment] 2021-03-20 17:45
> 
> 
> I don't have the problem right now, because I restarted my server, the spawners started working, but I'm sure it will stop again after a while. (Not everyone's spawners stop, it stop in a certain area.) I'll try if the problem happens again.

Perfect, make sure you let me here if it fixes the issue or not

**Comment by Requlogia** [comment] 2021-03-20 20:05
Spawner stopped working again. I tried what you said, but nothing changed.

**Comment by Requlogia** [comment] 2021-03-21 00:48
I have disabled many plugins on my server via the plugman plugin. Later, when I closed the Citizens plug-in, I encountered a problem like this, you can find its photo.
![npc eklentisi hatası](https://user-images.githubusercontent.com/77800395/111890190-3809e780-89f8-11eb-957b-5c41cb31b1a9.png)

**Comment by OmerBenGera** [comment] 2021-03-21 12:07
> 
> 
> I have disabled many plugins on my server via the plugman plugin. Later, when I closed the Citizens plugin, I encountered a problem like this, you can find its photo.
> ![npc eklentisi hatası](https://user-images.githubusercontent.com/77800395/111890190-3809e780-89f8-11eb-957b-5c41cb31b1a9.png)

Using plugman to disable plugins can cause issues without a restart.

**Comment by OmerBenGera** [comment] 2021-03-21 12:07
> 
> 
> Spawner stopped working again. I tried what you said, but nothing changed.

Try replicating the issue on a server with only WildStacker installed, and let me know what causes that

**Comment by OmerBenGera** [comment] 2021-03-21 12:23
Btw, how much time does it take for them to stop? after a few hours or..?

**Comment by Requlogia** [comment] 2021-03-21 12:26
Spawners' stop and rework times can vary, and as I said above, it happens in certain chunks and it can also vary.

**Comment by OmerBenGera** [comment] 2021-03-21 12:33
Wait, it happens only in the same specific chunks everytime?

**Comment by Requlogia** [comment] 2021-03-21 12:46
My troubled players are almost the same, but sometimes chunks can vary and I only have the problem with skeleton, zombie and zombie pigman spawners. Although the world and the chunks vary, the problem continues in general in the chunks I have observed. When I restart the server, it gets better, but it stops after a while and after a few hours / minutes the spawners keep running again.

**Comment by OmerBenGera** [comment] 2021-03-21 12:49
Well, you'll have to find a way to replicate it on another server or someone else can tell he has the same issue, otherwise I don't see how it's related to the plugin

**Comment by Requlogia** [comment] 2021-03-21 12:52
Although disabling a plugin another plugin did not work properly, I disabled almost all plugins. I have completely reset the file spigot/ bukkit/paper and server.properties file but did not see any changes.

**Comment by OmerBenGera** [comment] 2021-03-21 12:55
> 
> 
> Although disabling a plugin another plugin did not work properly, I disabled almost all plugins. I have completely reset the file spigot/ bukkit/paper and server.properties file but did not see any changes.

You disabled them using plugman. I need you to replicate the issue on another server, with only WildStacker installed - these are two different things.

**Comment by OmerBenGera** [comment] 2021-03-21 13:05
I released a new dev build that gives you the ability to completely disable WildStacker from overriding spawners.
Try it out, make sure you disable it under spawners-override. If it still occurs after disabling it, it means that WildStacker has nothing to do with the issue. If it stops from happening, I'll see what can cause it.

**Comment by Requlogia** [comment] 2021-03-22 04:46
I tested it for about 1 day by removing the WildStacker plug-in completely from my server and observed that it worked without any problems.

**Comment by OmerBenGera** [comment] 2021-03-22 08:04
> I tested it for about 1 day by removing the WildStacker plugin completely from my server and observed that it worked without any problems.

Thats not what I asked you to do.
Why arent you listening to my instructions?

**Comment by Requlogia** [comment] 2021-03-22 13:38
You keep saying that you don't have the problem, and you don't even want to know what my fault is. As a result of my tests, I realized that the source of the problem I was experiencing was the wildstacker. I will start using a different plugin by removing it completely from my server. You can try out the instructions yourself at the appropriate time.

**Comment by OmerBenGera** [comment] 2021-03-22 13:49
I told you to turn off the spawners overriding of the plugin and see if it fixes the issue. You just completely ignored my instructions.
Let me know after you actually listen to what I say, otherwise I have no way to help you.

**Comment by OmerBenGera** [comment] 2021-03-22 13:51
Its like the third time you do whatever you want, only in this report. If you cant listen and do what you asked to do, why do I need to waste my time on this report? It makes no sense.

**Comment by Requlogia** [comment] 2021-03-22 14:10
You shouldn't expect me to test the way you say an error that I know was caused by the plugin and I don't know when it will happen again. I have already tested most things that I can test. Won't you fix the problem when a lot of people live? So why are so many people buying the plugin?

**Comment by OmerBenGera** [comment] 2021-03-22 14:24
> You shouldn't expect me to test the way you say an error that I know was caused by the plugin and I don't know when it will happen again. I have already tested most things that I can test. Won't you fix the problem when a lot of people live? So why are so many people buying the plugin?

You are again ignoring what I wrote.
As I said before, I released a new jar that you can disable the plugin from overriding spawners behvaior, which should fix the issue. You just need to turn the spawners override to false in the config, reload the plugin and wait.
If it fixes the issue, I will implement more tools that can help with finding the cause of the issue.
What else do you want me to do lmao, thats the best way to find and fix the issue. If you dont like it, then just close the issue so neither of us waste more time on that.

**Closed** 2021-03-22 14:35 UTC
Labels: Bug Report, Lacks information, Needs investigation
