### ISSUE TITLE
incompatibility plugin 

### ISSUE THREAD

**Issue by Distolfix** [OmerBenGera/WildStacker#50] opened 2021-02-16 08:09 UTC
When i use this plugin https://www.spigotmc.org/resources/%E2%9C%A8upgradablespets-1-7-1-16-x-%E2%9C%A8-mysql-mongodb-levels-guis-effects.46406/
The plugin WildStacker is incompatible
Because the pet it has no life and many other bugs, while if I disable WildStacker it works correctly.

**Comment by Distolfix** [comment] 2021-02-16 08:10
Version WildStacker the latest 
Server 1.8.8 paperspigot

**Comment by OmerBenGera** [comment] 2021-02-16 09:58
What exactly doesn't work?

**Comment by Distolfix** [comment] 2021-02-16 10:00
The life, when i hit a pet the pet instantly died and i can hit the pet if I disable the wildstacker plugin everything works, as it should

**Comment by OmerBenGera** [comment] 2021-02-16 10:04
Pets should not die at all?

**Comment by Distolfix** [comment] 2021-02-16 10:05
The pet die after one hit of a sword even if I increase his life. and i can hit my own pet if i disable the plugins all wark. please fix this

**Comment by Distolfix** [comment] 2021-02-16 10:06
if i disable WildStacker all work.. Please fix bro

**Comment by Distolfix** [comment] 2021-02-16 10:11
Can i have your telegram id? so we discuss them for the problem?

**Comment by OmerBenGera** [comment] 2021-02-16 10:20
Maybe you have one shot enabled?

**Comment by Distolfix** [comment] 2021-02-16 10:21
Nope, bro i used the default config i tried to delete all directory, and i started the server with all default configs and directory not work

**Comment by Distolfix** [comment] 2021-02-16 10:23
obviously the directory of WildStacker, i talked with the developer of the plugin of pet about the bug and is a conflict with your plugin

**Comment by Distolfix** [comment] 2021-02-16 10:24
I would prefer you to add compatibility as soon as possible, as I am unable to use this pet plugin

**Comment by OmerBenGera** [comment] 2021-02-16 10:26
Just relax and be patient. I tried to understand what the issue is, and I'll see if I can do anything with that, as WildStacker doesn't change damage of tools... Send me your WildStacker config by uploading it to youtube

**Comment by Distolfix** [comment] 2021-02-16 10:27
It's okay

**Comment by Distolfix** [comment] 2021-02-16 10:54
Look this video bro https://youtu.be/YvK7IP4am30

**Comment by Distolfix** [comment] 2021-02-16 10:58
as you can see i deleted all directory on moba x term

**Comment by OmerBenGera** [comment] 2021-02-16 11:06
Just relax and be patient. I tried to understand what the issue is, and I'll see if I can do anything with that, as WildStacker doesn't change damage of tools... Send me your WildStacker config by uploading it to pastebin

**Comment by Distolfix** [comment] 2021-02-16 11:07
it's default config bro

**Comment by Distolfix** [comment] 2021-02-16 11:07
Look the video

**Comment by Distolfix** [comment] 2021-02-16 11:08
https://pastebin.com/LRzgRdYk

**Comment by OmerBenGera** [comment] 2021-02-16 11:43
I saw the video, and as I said twice already, I will check it out.
Just take a deep breath and be patient.
Also, the plugin is premium, so tag me on discord and I'll open a ticket for you so you can give me a copy of the jar.

**Comment by Distolfix** [comment] 2021-02-16 11:48
Please send a message to me on discord my id is Distolfix#2975

**Comment by Distolfix** [comment] 2021-02-16 11:52
How will I receive updates?

**Comment by OmerBenGera** [comment] 2021-02-16 12:00
I will let you know once it's pushed or there's new information needed to be provided.

**Comment by Distolfix** [comment] 2021-02-16 12:01
I sent it to you on discord

**Comment by OmerBenGera** [comment] 2021-02-16 12:05
Bro, I know you sent me the jar, just be patient. I am not working for you, and if you keep asking me when it will be fixed, I'll just delay the time I'll check it out. Stop being annoying and just be patient.

**Comment by Distolfix** [comment] 2021-02-16 12:08
I simply asked you to let me know when you have news

**Comment by OmerBenGera** [comment] 2021-02-16 12:27
> 
> 
> I simply asked you to let me know when you have news

And I answered to that already as well.

**Comment by Distolfix** [comment] 2021-02-16 12:50
I look forward to hearing from you.  thank you

Il mar 16 feb 2021, 13:27 Ome_R <notifications@github.com> ha scritto:

**Comment by Distolfix** [comment] 2021-02-16 15:47
Dear Omer, I've been testing and doing mob stacks false; it works. This means you need to make the mob stacker compatible with the pet plugin

**Comment by OmerBenGera** [comment] 2021-02-18 16:57
I spawned a pet and tried to hit my pet, however it's not possible due to the pets plugin blocking it.
Not sure what the issue is.

**Comment by Distolfix** [comment] 2021-02-18 17:00
have you tried to replicate the bug?  with the sword? I talked to the pet
developer and she told me she needs to develop the compatible version.

Il gio 18 feb 2021, 17:57 Ome_R <notifications@github.com> ha scritto:

**Comment by OmerBenGera** [comment] 2021-02-18 17:04
I spawned a pet, tried to hit it with a diamond sword and everything worked just fine.

**Comment by Distolfix** [comment] 2021-02-18 17:05
Man, I will keep you updated, I will do all the necessary checks

Il gio 18 feb 2021, 18:04 Ome_R <notifications@github.com> ha scritto:

**Comment by OmerBenGera** [comment] 2021-02-18 17:07
Great, let me know how to replicate it. Might have done something wrong, idk.
I used default files of both plugins

**Comment by OmerBenGera** [comment] 2021-02-27 13:28
Any news regarding this?

**Comment by Distolfix** [comment] 2021-02-27 17:04
In this moment we deactivated the mob stacking. we would like you to make
the plug-in compatible anyway in order to enable mob stacking

Il sab 27 feb 2021, 14:28 Ome_R <notifications@github.com> ha scritto:

**Comment by OmerBenGera** [comment] 2021-02-27 17:21
I am closing this issue then, as from my testings everything worked fine and there are no issues with the plugins.
You couldn't let me know how to replicate the issue, and therefore it cannot be fixed.

**Closed by OmerBenGera** 2021-02-27 17:21 UTC
Labels: Bug Report, Needs investigation
