### ISSUE TITLE
EntityDeathEvent clear drops

### ISSUE THREAD

**Issue by TheCrappiest** [OmerBenGera/WildStacker#99] opened 2021-03-27 09:35 UTC
**Minecraft's Version**
1.8.8-R0.1-SNAPSHOT

**Plugin's Version**: -
Stable: 3.5.1
Dev Build: #100

**Describe the bug**
When running EntityDeathEvent I clear the drops but they still spawn the items. Removing wildstacker stops this from occurring.

**To Reproduce**
Create a listener using EntityDeathEvent, run event.getDrops().clear();, Watch as items still spawn. (EventPriority low was also tested.)

**Comment by OmerBenGera** [comment] 2021-03-27 11:33
I can't seem to replicate the issue - it works as intended in 1.8.8 with only WS installed.

**Comment by TheCrappiest** [comment] 2021-03-27 11:42
![image](https://user-images.githubusercontent.com/71765513/112719590-9a1a8f00-8ec7-11eb-8351-bb3f94784f5f.png)
![image](https://user-images.githubusercontent.com/71765513/112719603-a9014180-8ec7-11eb-864b-48968e77b074.png)

**Comment by OmerBenGera** [comment] 2021-03-27 11:49
As I said earlier, I tried to replicate the issue and couldn't.
When clearing the drops, no drops are dropped. I tested it with cows, not iron golems tho.
Let me know if cows work for you (no minions, no nothing)

**Comment by TheCrappiest** [comment] 2021-03-27 11:52
Yeah works correctly when player kills the golem. Just not when a custom damage is applied it looks like.
((Damageable) mobs).damage(((Damageable) mobs).getMaxHealth());

**Comment by OmerBenGera** [comment] 2021-03-27 11:54
This is probably an issue with 1.8.8 and how hitting entities is calculated.
I don't think it's possible to be fixed on my end.

**Comment by OmerBenGera** [comment] 2021-03-27 11:56
By the way, Damageable is not a valid class for entities.

**Comment by TheCrappiest** [comment] 2021-03-27 11:56
Yeah its the damage cause it looks like...
![image](https://user-images.githubusercontent.com/71765513/112719917-75bfb200-8ec9-11eb-8b1d-b3cc9d2760cb.png)
![image](https://user-images.githubusercontent.com/71765513/112719921-7d7f5680-8ec9-11eb-82c0-a379280cc068.png)
Canceling the damage event and running the custom damage causes the issue as well.

**Comment by TheCrappiest** [comment] 2021-03-27 11:56
> By the way, Damageable is not a valid class for entities.

It is for 1.8.8

**Comment by OmerBenGera** [comment] 2021-03-27 11:57
>  Canceling the damage event and running the custom damage causes the issue as well.

Add a tick delay, check if it fixes the issue.

**Comment by TheCrappiest** [comment] 2021-03-27 12:01
Setting EventPriority to high as well as adding a delay of any tick amount does not fix it.

**Comment by OmerBenGera** [comment] 2021-03-27 12:03
That's not what I meant. I meant to add delay to the damage task.
You can't clear the drops in a delay - they were already processed by the time your task is executed.
Also, priorities has nothing to do with the issue, as WS isn't listening to the event or changing it in any way.

**Comment by TheCrappiest** [comment] 2021-03-27 12:05
What do you mean add a delay to the damage task? Once it damages it runs the entitydeath event because its killing the entity.

**Comment by OmerBenGera** [comment] 2021-03-27 12:06
> 
> 
> Yeah its the damage cause it looks like...
> ![image](https://user-images.githubusercontent.com/71765513/112719917-75bfb200-8ec9-11eb-8b1d-b3cc9d2760cb.png)
> ![image](https://user-images.githubusercontent.com/71765513/112719921-7d7f5680-8ec9-11eb-82c0-a379280cc068.png)
> Canceling the damage event and running the custom damage causes the issue as well.

Look here - you call the damage method inside an already ongoing damage task (aka in the damage event).
Add a 1-tick delay so your damage method isn't called inside the event.

**Comment by OmerBenGera** [comment] 2021-03-27 12:08
Never mind, I tested it and when calling damage the drops still drop.
I will check it out

**Comment by TheCrappiest** [comment] 2021-03-27 12:11
> Never mind, I tested it and when calling damage the drops still drop.
> I will check it out

Yeah and a delay wouldn't matter much since the event was cancelled so the listeners running after mine will see its cancelled.
And then also a delay wouldn't change how the butcher kills anyway cause it would still bein running the damage method.

**Comment by OmerBenGera** [comment] 2021-03-27 12:15
> 
> 
> > Never mind, I tested it and when calling damage the drops still drop.
> > I will check it out
> 
> Yeah and a delay wouldn't matter much since the event was cancelled so the listeners running after mine will see its cancelled.
> And then also a delay wouldn't change how the butcher kills anyway cause it would still bein running the damage method.

Many times you can't run the same task when it's already running, so I thought that was a similar case.
However, I called the damage method in another place and it seem to still happen, and I think I know why.

**Comment by TheCrappiest** [comment] 2021-03-27 12:16
> Many times you can't run the same task when it's already running, so I thought that was a similar case.
I know if I cancel the event all listeners that run after mine will see that it was cancelled lol. Thats why I said a delay wouldn't matter. (Unless they don't check for cancelled and still add drops to the list.)

**Comment by OmerBenGera** [comment] 2021-03-27 12:23
> 
> 
> > Many times you can't run the same task when it's already running, so I thought that was a similar case.
> 
> I know if I cancel the event all listeners that run after mine will see that it was cancelled lol. Thats why I said a delay wouldn't matter. (Unless they don't check for cancelled and still add drops to the list.)

It really doesn't matter - I am not talking about listeners, I am talking about the nms code.
Anyways that's not the case, and I already found the issue.

**Comment by TheCrappiest** [comment] 2021-03-27 12:25
> Anyways that's not the case, and I already found the issue.

Perfect. Thanks.

**Comment by OmerBenGera** [comment] 2021-03-27 12:31
Check out latest dev build, it should be fixed.

**Comment by TheCrappiest** [comment] 2021-03-27 13:22
Yeap that seems to have fixed it.

**Comment by OmerBenGera** [comment] 2021-03-27 14:03
> 
> 
> Yeap that seems to have fixed it.
> Well... it fixed that issue but now when I kill a stack of 999 it doesn't drop all the items... only the amount for 1 kill.

What's your code

**Comment by TheCrappiest** [comment] 2021-03-27 14:21
![image](https://user-images.githubusercontent.com/71765513/112723679-d1943600-8edd-11eb-903e-89d9887f6331.png)

**Comment by OmerBenGera** [comment] 2021-03-27 14:23
Where are you adding drops?

**Comment by OmerBenGera** [comment] 2021-03-27 14:24
Or I just don't understand the issue now

**Comment by TheCrappiest** [comment] 2021-03-27 14:24
The second line in the event creates a new list and the 3rd, 4th and 5th is to add the events drops to the list.

**Comment by OmerBenGera** [comment] 2021-03-27 14:29
You don't add anywhere drops to the event's drops list...

**Comment by TheCrappiest** [comment] 2021-03-27 14:29
> You don't add anywhere drops to the event's drops list...

I don't add drops to the entitydeathevent list I make my own.

**Comment by OmerBenGera** [comment] 2021-03-27 14:30
If you mean that event#getDrops don't have the drops of stacked entities, then you're right.
This event isn't handled by WildStacker, it's fired due to your damage method and I can't do anything with that.
You can use StackedEntity#getDrops to get the drops based on stack size.

**Comment by TheCrappiest** [comment] 2021-03-27 14:32
> If you mean that event#getDrops don't have the drops of stacked entities, then you're right.
> This event isn't handled by WildStacker, it's fired due to your damage method and I can't do anything with that.
> You can use StackedEntity#getDrops to get the drops based on stack size.

Yeah was hoping not to have to do that as I would have to recode that whole eventlistener. IDK what you changed since this last worked lol I haven't messed with this code for a few months atleast, only recently started occurring.

**Comment by OmerBenGera** [comment] 2021-03-27 14:37
I didn't change anything.
When calling the damage method, there's no damage event if the entity is killed. Even WildStacker listens to this custom event and handles it, as there's nothing to be done regarding this. You can see here the listener:
https://github.com/OmerBenGera/WildStacker/blob/dev/src/main/java/com/bgsoftware/wildstacker/listeners/EntitiesListener.java#L159

**Comment by TheCrappiest** [comment] 2021-03-27 14:44
https://github.com/OmerBenGera/WildStacker/blob/dev/src/main/java/com/bgsoftware/wildstacker/listeners/EntitiesListener.java#L465

At this line it looks like you are dropping items. This might be the reason it spawns the items and doesn't clear. Unless I'm reading this method wrong.

**Comment by OmerBenGera** [comment] 2021-03-27 14:53
> 
> 
> https://github.com/OmerBenGera/WildStacker/blob/dev/src/main/java/com/bgsoftware/wildstacker/listeners/EntitiesListener.java#L465
> 
> At this line it looks like you are dropping items. This might be the reason it spawns the items and doesn't clear. Unless I'm reading this method wrong.

You're looking at the wrong place. This is when vanilla hit occurs. As you can see, the plugin cancels the last damage, calls EntityDeathEvent and handles everything on it's own. However, whne you run Damageable#damage, there's no damage event. However, if the entity dies, the vanilla EntityDeathEvent is still fired. Therefore, the plugin catches it in the line I sent above (it knows that its not it's own event due to the dead entity check) and calls the method of last damage with custom event. However, the death event in this time isn't called again, and the drops from this event are copied to there and the drops are calculated.
That's the reason why your event#getDrops is returning vanilla drops - WildStacker never fired this event, and therefore the drops of it aren't calculated. WildStacker calculates the drops later, after your calculations.

**Comment by TheCrappiest** [comment] 2021-03-27 14:56
> You're looking at the wrong place. This is when vanilla hit occurs. As you can see, the plugin cancels the last damage, calls EntityDeathEvent and handles everything on it's own. However, whne you run Damageable#damage, there's no damage event. However, if the entity dies, the vanilla EntityDeathEvent is still fired. Therefore, the plugin catches it in the line I sent above (it knows that its not it's own event due to the dead entity check) and calls the method of last damage with custom event. However, the death event in this time isn't called again, and the drops from this event are copied to there and the drops are calculated.
That's the reason why your event#getDrops is returning vanilla drops - WildStacker never fired this event, and therefore the drops of it aren't calculated. WildStacker calculates the drops later, after your calculations.

Alright well that sucks that it just stopped working properly all of a sudden. I'll just have to bite the bullet and recode that.

**Comment by OmerBenGera** [comment] 2021-03-27 14:56
Or in other words - everything is due to the damage method not firing any event.
WildStacker aims to handle deaths on it's own so all drops from other plugins will work on the time, and it fails in one place - when calling this method.

**Comment by OmerBenGera** [comment] 2021-03-27 15:04
> 
> 
> > You're looking at the wrong place. This is when vanilla hit occurs. As you can see, the plugin cancels the last damage, calls EntityDeathEvent and handles everything on it's own. However, whne you run Damageable#damage, there's no damage event. However, if the entity dies, the vanilla EntityDeathEvent is still fired. Therefore, the plugin catches it in the line I sent above (it knows that its not it's own event due to the dead entity check) and calls the method of last damage with custom event. However, the death event in this time isn't called again, and the drops from this event are copied to there and the drops are calculated.
> > That's the reason why your event#getDrops is returning vanilla drops - WildStacker never fired this event, and therefore the drops of it aren't calculated. WildStacker calculates the drops later, after your calculations.
> 
> Alright well that sucks that it just stopped working properly all of a sudden. I'll just have to bite the bullet and recode that.

This was a known issue from the beginning, I never changed anything regarding this or I even can - it's just the way bukkit's code was implemented. It might have been fixed in newer versions and that's why you didn't notice, however I am not sure

**Comment by OmerBenGera** [comment] 2021-03-27 15:20
By the way, you can easily fix it by calling the EntityDamageEvent on your own, check if it's cancelled or not, and take the damage value from the event. This should fix everything.

I am closing this for now :)

**Closed by OmerBenGera** 2021-03-27 15:20 UTC
Labels: Bug Report, Potential fix
